// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qybcjpopvqhufqxysvug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5YmNqcG9wdnFodWZxeHlzdnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTcwMTYsImV4cCI6MjA2NTEzMzAxNn0.adeHVhs-Ku-bvAPLgyH7PEM00oxQvMEvsqOnBQZVAo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);